#!/usr/bin/env bash

# Clone of sherlock in bash

# Check user
if [[ ! "$*" ]]; then
  echo "usage: shellock [user]" >&2
  exit 0
fi

user="$*"
sherlock_url='https://raw.githubusercontent.com/sherlock-project/sherlock/842ae1f754c7af46f06dd31ae168c1d9793da768/sherlock_project/resources/data.json'
timeout=10
curl_opts=(-s --max-time $timeout --connect-timeout $timeout)
sherlock_data=$(curl "${curl_opts[@]}" "$sherlock_url")
# sherlock_data=$(<data.json) # Test local

# Print header
print_header() {
  echo -e "\nChecking username $(tput setaf 4)$user$(tput sgr0) on:\n"
}

# Print result
print_result() {
  echo -e "\nAccounts searched: $(tput setaf 4)${1}$(tput sgr0)"
  echo "Accounts founds: $(tput setaf 2)${2}$(tput sgr0)"
  echo "Accounts not founds: $(tput setaf 1)${3}$(tput sgr0)"
}

# Print status
print_status() {
  local status=$1
  local site_name=$2
  local url=$3

  case $1 in
    found)
      echo "[$(tput setaf 2)+$(tput sgr0)] $(tput setaf 2)$site_name:$(tput sgr0) $url" ;;

    not_found)
      echo "[$(tput setaf 1)-$(tput sgr0)] $(tput setaf 1)$site_name:$(tput sgr0) $url" ;;
  esac
}

# Header
print_header

# Body
readarray -t sites < <(awk -F'"' '/": \{/ {print $2}' <<< "$sherlock_data")
readarray -t urls < <(awk -F'"' '/"url":/ {print $4}' <<< "$sherlock_data")

for site_name in "${sites[@]}"; do
  url=${urls[site_count]//\{\}/$user}
  http_code=$(curl -Isq "$url" | awk '/^HTTP/ {print $2}')

  if [[ $http_code -eq 200 ]]; then
    status=found
    ((site_valid_count++))
  else
    status=not_found
    ((site_invalid_count++))
  fi

  print_status $status "$site_name" "$url"
  ((site_count++))
done

# Result
print_result $site_count $site_valid_count $site_invalid_count
